version: '3'
services:
  mariadb:
    image: 'mariadb'
    container_name: 'database'
    hostname: 'mariadb'
    ports:
      - '3346:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=iesalixar
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=daw2tarde
      - MYSQL_PASSWORD=daw2tarde
    volumes:
      - 'data:/var/lib/mysql'
  apachephp:
    #image: 'php:7.2-apache'
    # Para usar una vez hayamos explicado lo que es docker build
    image: 'iesalixar/php72mysqli'
    container_name: 'webserver'
    hostname: 'apache'
    ports:
      - '9090:80'
    volumes: 
      - 'webfolder:/var/www/html'
    depends_on: 
      - mariadb
    # Si queremos que funcionen la aplicaciones que use mysqli debemos instalar ese módulo de php con 
    # el siguiente comando que viene dentro del contenedor
    # docker-php-ext-install mysqli
    # Podemos comprobar que está instalado con php -m
    # Tras instalarlo debemos reiniciar el servicio
    # Recodar que todo lo que está en /var/www/html debe pertencer al usuario www-data 
volumes:
  webfolder:
    driver: local
  data:
    driver: local 